In [560]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import re
import scipy.stats

In [576]:
data = pd.read_csv("ZCruit_Cleaned_Data.csv")

C:\Users\AlvinYu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (15,17,19,21,23,25,27,29,31,33) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [566]:
data

,Full Name,Last Name,Grad Year,Position,Height,Height Source,Weight,Weight Source,Zcruit Rating,Committed To,...,Hand Size Source,Powerball Toss,Powerball Toss Source,SPARQ Rating,SPARQ Rating Source,GPA,ACT,SAT,Unnamed: 37,Unnamed: 38
0,Korey Foreman,Foreman,2021,DE,"6' 4""",nike_opening,248.0,nike_opening,96.6970,USC,...,NaN,44.5,nike_opening,98.76,nike_opening,3.03,NaN,NaN,NaN,NaN
1,J.T. Tuimoloau,Tuimoloau,2021,DE,"6' 4""",national_preps,275.0,national_preps,96.6970,NaN,...,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN
2,JC Latham,Latham,2021,OT,"6' 6""",national_preps,279.0,nike_opening,96.6970,Alabama,...,NaN,NaN,NaN,NaN,NaN,2.35,NaN,NaN,NaN,NaN
3,Emeka Egbuka,Egbuka,2021,WR,"6' 0.5""",nike_opening,190.0,nike_opening,96.3939,Ohio State,...,national_combine,41.0,nike_opening,NaN,NaN,4.00,NaN,NaN,NaN,NaN
4,Dallas Turner,Turner,2021,DE,"6' 2.5""",rivals_camp,223.0,rivals_camp,96.3939,Alabama,...,rivals_camp,NaN,NaN,NaN,NaN,3.70,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71365,Carl Collins III,Collins III,2022,WR,"4' 8""",rivals,86.0,rivals,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71366,Antrone\t Coston,Coston,2024,WR,"5' 1""",rivals,85.0,rivals,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71367,Gerald\t Lampkin,Lampkin,2024,WR,"4' 11""",rivals,84.0,rivals,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71368,Jaeden\t Hamm,Hamm,2024,WR,"4' 10""",rivals,80.0,rivals,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71369,Eugene Thomas,Thomas,2022,RB,"4' 9""",rivals,71.0,rivals,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [567]:
height_regex = "^(\d)'\s*(\d*\.*\d*)"
def height_str_to_val(height_str):
    match = re.match("^(\d)'\s*(\d*\.*\d*)", height_str)
    groups = match.groups()
    feet, inches = int(groups[0]), float(groups[1])
    return feet * 12 + inches

In [568]:
data['Height'] = data['Height'].apply(height_str_to_val)

In [306]:
data.head()

,Full Name,Last Name,Grad Year,Position,Height,Height Source,Weight,Weight Source,Zcruit Rating,Committed To,...,Hand Size Source,Powerball Toss,Powerball Toss Source,SPARQ Rating,SPARQ Rating Source,GPA,ACT,SAT,Unnamed: 37,Unnamed: 38
0,Korey Foreman,Foreman,2021,DE,76.0,nike_opening,248.0,nike_opening,96.6970,USC,...,NaN,44.5,nike_opening,98.76,nike_opening,3.03,NaN,NaN,NaN,NaN
1,J.T. Tuimoloau,Tuimoloau,2021,DE,76.0,national_preps,275.0,national_preps,96.6970,NaN,...,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN
2,JC Latham,Latham,2021,OT,78.0,national_preps,279.0,nike_opening,96.6970,Alabama,...,NaN,NaN,NaN,NaN,NaN,2.35,NaN,NaN,NaN,NaN
3,Emeka Egbuka,Egbuka,2021,WR,72.5,nike_opening,190.0,nike_opening,96.3939,Ohio State,...,national_combine,41.0,nike_opening,NaN,NaN,4.00,NaN,NaN,NaN,NaN
4,Dallas Turner,Turner,2021,DE,74.5,rivals_camp,223.0,rivals_camp,96.3939,Alabama,...,rivals_camp,NaN,NaN,NaN,NaN,3.70,NaN,NaN,NaN,NaN

In [307]:
QB = data[data['Position'] == 'QB']

In [308]:
# .shape --> number of rows and columns

qb = QB[['Full Name', 'Height', 'Weight', 'Wingspan', 'Hand Size', 'Powerball Toss']]
qb

             Full Name  Height  Weight  Wingspan  Hand Size  Powerball Toss
9       Caleb Williams   73.00   209.0       NaN        NaN             NaN
14           Sam Huard   74.00   180.0       NaN        NaN             NaN
29         Ty Thompson   75.25   209.0      75.0        NaN            36.0
39         Kyle McCord   74.00   207.5      73.0       9.45            31.0
40       J.J. McCarthy   74.00   181.0      74.5       8.66             NaN
...                ...     ...     ...       ...        ...             ...
71298  Jkylon\t Ceasar   64.00   112.0       NaN        NaN             NaN
71310       Alvis Shaw   65.00   110.0       NaN        NaN             NaN
71314      Henry\t Lee   64.00   110.0       NaN        NaN             NaN
71344   Joe Villarreal   61.00   101.0       NaN        NaN             NaN
71364   Jayden Terrell   60.00    86.0       NaN        NaN             NaN

[6345 rows x 6 columns]

In [309]:
qb[qb['Wingspan'].isna()].shape

(6025, 6)

In [310]:
qb[qb['Hand Size'].isna()].shape

(6042, 6)

In [311]:
# .corr() --> function to find correlations
# wingspan --> linear regression using height and weight
# hand size --> median


qb.corr()

                  Height    Weight  Wingspan  Hand Size  Powerball Toss
Height          1.000000  0.642136  0.628396   0.017558        0.555265
Weight          0.642136  1.000000  0.431284   0.071545        0.474163
Wingspan        0.628396  0.431284  1.000000   0.044624        0.181512
Hand Size       0.017558  0.071545  0.044624   1.000000       -0.032712
Powerball Toss  0.555265  0.474163  0.181512  -0.032712        1.000000

In [312]:
training_data = qb[qb['Wingspan'].notna()]
training_data

           Full Name  Height  Weight  Wingspan  Hand Size  Powerball Toss
29       Ty Thompson   75.25   209.0     75.00        NaN            36.0
39       Kyle McCord   74.00   207.5     73.00       9.45            31.0
40     J.J. McCarthy   74.00   181.0     74.50       8.66             NaN
58        Drake Maye   76.00   202.5     75.50       8.66             NaN
65       Jake Garcia   73.00   194.0     75.75       8.66            30.0
...              ...     ...     ...       ...        ...             ...
33457    Maddox Kopp   77.00   212.0     77.50       9.06             NaN
33465    Bauer Sharp   76.00   213.0     77.75       9.06             NaN
33479   Nate Yarnell   78.25   195.0     78.50       9.45             NaN
33484   Daniel Shoch   74.00   203.0     78.50       9.06             NaN
33508   Tevin Carter   73.50   201.0     80.50       8.66             NaN

[320 rows x 6 columns]

In [313]:
qb_train = training_data[['Height', 'Weight', 'Wingspan']]
qb_train

       Height  Weight  Wingspan
29      75.25   209.0     75.00
39      74.00   207.5     73.00
40      74.00   181.0     74.50
58      76.00   202.5     75.50
65      73.00   194.0     75.75
...       ...     ...       ...
33457   77.00   212.0     77.50
33465   76.00   213.0     77.75
33479   78.25   195.0     78.50
33484   74.00   203.0     78.50
33508   73.50   201.0     80.50

[320 rows x 3 columns]

In [314]:
# linear regression -->  y = ax1 + bx2

from sklearn.linear_model import LinearRegression

In [315]:
X = qb_train[['Height', 'Weight']]
Y = qb_train['Wingspan']

In [316]:
test_qb = qb[qb['Wingspan'].isna()]

In [317]:
reg = LinearRegression(normalize = True).fit(X,Y)
test_qb["Predicted Wingspan"] = reg.predict(test_qb[['Height', 'Weight']])

<ipython-input-317-8ae9ac636c4c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_qb["Predicted Wingspan"] = reg.predict(test_qb[['Height', 'Weight']])

In [318]:
test_qb

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Predicted Wingspan
9,Caleb Williams,73.0,209.0,NaN,NaN,NaN,74.990767
14,Sam Huard,74.0,180.0,NaN,NaN,NaN,75.079550
128,Preston Stone,74.0,215.0,NaN,NaN,NaN,75.836542
147,Luke Adcock,75.0,200.0,NaN,NaN,NaN,76.228122
155,Nico Iamaleava,77.0,188.0,NaN,NaN,NaN,77.400592
...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.0,112.0,NaN,NaN,NaN,66.448772
71310,Alvis Shaw,65.0,110.0,NaN,NaN,NaN,67.121520
71314,Henry\t Lee,64.0,110.0,NaN,NaN,NaN,66.405515
71344,Joe Villarreal,61.0,101.0,NaN,NaN,NaN,64.062845
71364,Jayden Terrell,60.0,86.0,NaN,NaN,NaN,63.022415

In [319]:
reg.coef_

array([0.71600504, 0.02162835])

In [320]:
training_data["Predicted Wingspan"] = reg.predict(training_data[['Height', 'Weight']])

<ipython-input-320-257b81e20b0d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_data["Predicted Wingspan"] = reg.predict(training_data[['Height', 'Weight']])

In [321]:
training_data

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Predicted Wingspan
29,Ty Thompson,75.25,209.0,75.00,NaN,36.0,76.601779
39,Kyle McCord,74.00,207.5,73.00,9.45,31.0,75.674330
40,J.J. McCarthy,74.00,181.0,74.50,8.66,NaN,75.101179
58,Drake Maye,76.00,202.5,75.50,8.66,NaN,76.998198
65,Jake Garcia,73.00,194.0,75.75,8.66,30.0,74.666342
...,...,...,...,...,...,...,...
33457,Maddox Kopp,77.00,212.0,77.50,9.06,NaN,77.919672
33465,Bauer Sharp,76.00,213.0,77.75,9.06,NaN,77.225296
33479,Nate Yarnell,78.25,195.0,78.50,9.45,NaN,78.446997
33484,Daniel Shoch,74.00,203.0,78.50,9.06,NaN,75.577002
33508,Tevin Carter,73.50,201.0,80.50,8.66,NaN,75.175743

In [322]:
>>> from sklearn.metrics import mean_squared_error

In [323]:
error = mean_squared_error(training_data['Wingspan'], training_data['Predicted Wingspan'])

In [324]:
np.sqrt(error)

2.181586574281995

In [325]:
np.mean(training_data['Wingspan'])

74.00703125

In [326]:
qb

             Full Name  Height  Weight  Wingspan  Hand Size  Powerball Toss
9       Caleb Williams   73.00   209.0       NaN        NaN             NaN
14           Sam Huard   74.00   180.0       NaN        NaN             NaN
29         Ty Thompson   75.25   209.0      75.0        NaN            36.0
39         Kyle McCord   74.00   207.5      73.0       9.45            31.0
40       J.J. McCarthy   74.00   181.0      74.5       8.66             NaN
...                ...     ...     ...       ...        ...             ...
71298  Jkylon\t Ceasar   64.00   112.0       NaN        NaN             NaN
71310       Alvis Shaw   65.00   110.0       NaN        NaN             NaN
71314      Henry\t Lee   64.00   110.0       NaN        NaN             NaN
71344   Joe Villarreal   61.00   101.0       NaN        NaN             NaN
71364   Jayden Terrell   60.00    86.0       NaN        NaN             NaN

[6345 rows x 6 columns]

In [327]:
def create_percentile(position, event):
    """Take in a position - CB, WR, QB, etc. and an event - Fourty Yard Dash, Weight, 3 Cone and return a list of percentile values
        of 0, 10th, ... 100th percentile. Reverse for all speed events (lower is better) such as 40, 3 Cone, and Shuttle."""
    sorted_athletes = data[data['Position'] == position]     
    event_values = (sorted_athletes[event].astype(float)).dropna()
    percentile = []
    for i in np.arange(0, 1.01, 0.05):
        percentile.append(event_values.quantile(i))
    if (event == "Forty Yard Dash") or (event == "Shuttle") or (event == "3 Cone"):
        return percentile[::-1]
    return percentile

In [328]:
percentiles = create_percentile('QB', 'Height')
percentiles

[57.0,
 67.0,
 68.0,
 69.0,
 70.0,
 70.0,
 70.0,
 71.0,
 71.0,
 72.0,
 72.0,
 72.0,
 72.0,
 73.0,
 73.0,
 74.0,
 74.0,
 74.0,
 75.0,
 76.0,
 80.0]

In [329]:
 scipy.stats.percentileofscore(percentiles, 75, kind='rank')

90.47619047619048

In [330]:
metric_dict = {}
for metric in qb.columns[1:5]:
    metric_dict[metric] = create_percentile('QB', metric)

In [331]:
metric_dict['Hand Size']

[7.09,
 8.25,
 8.27,
 8.66,
 8.66,
 8.66,
 8.816,
 9.0,
 9.06,
 9.06,
 9.06,
 9.25,
 9.45,
 9.45,
 9.84,
 10.14,
 21.0,
 22.0,
 23.0,
 23.0,
 27.0]

In [332]:
def value_to_percentile(event, value, metric_dict):
    if (event == "Forty Yard Dash") or (event == "Shuttle") or (event == "3 Cone"):
        return round((100 - scipy.stats.percentileofscore(metric_dict[event], value, kind='rank')), 2)
    else:
        return round((scipy.stats.percentileofscore(metric_dict[event], value, kind='rank')), 2)

In [470]:
def percentile_to_value(event, percentile, metric_dict):
     if (event == "Forty Yard Dash") or (event == "Shuttle") or (event == "3 Cone"):
        return scipy.stats.scoreatpercentile(metric_dict[event], 100 - percentile)
     else:
        return scipy.stats.scoreatpercentile(metric_dict[event], percentile)

In [334]:
def add_score(metric, data, metric_dict):
    # data = data.dropna()
    data[metric + " " + "Percentile"] = data.apply(lambda x: value_to_percentile(metric, x[metric], metric_dict), axis = 1)
    return data

In [336]:
data_new = qb
chosen_metrics = data_new.columns[1:5]
for metric in chosen_metrics:
    data_new = add_score(metric, data_new, metric_dict)

<ipython-input-334-531b2ac81a5e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric + " " + "Percentile"] = data.apply(lambda x: value_to_percentile(metric, x[metric], metric_dict), axis = 1)

In [337]:
chosen_metrics

Index(['Height', 'Weight', 'Wingspan', 'Hand Size'], dtype='object')

In [338]:
test_handsize = data_new[data_new['Hand Size'].isna()]
test_handsize

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,NaN,NaN,NaN,69.05,90.48,NaN,NaN
14,Sam Huard,74.00,180.0,NaN,NaN,NaN,80.95,64.29,NaN,NaN
29,Ty Thompson,75.25,209.0,75.00,NaN,36.0,90.48,90.48,64.29,NaN
96,Tyler Buchner,72.50,206.0,72.25,NaN,37.5,61.90,90.48,28.57,NaN
113,Malachi Nelson,73.50,175.0,77.00,NaN,NaN,71.43,54.76,85.71,NaN
...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71310,Alvis Shaw,65.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71314,Henry\t Lee,64.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71344,Joe Villarreal,61.00,101.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71364,Jayden Terrell,60.00,86.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN

In [339]:
only_percentiles = test_handsize[['Height Percentile', 'Weight Percentile', 'Wingspan Percentile']]
only_percentiles

       Height Percentile  Weight Percentile  Wingspan Percentile
9                  69.05              90.48                  NaN
14                 80.95              64.29                  NaN
29                 90.48              90.48                64.29
96                 61.90              90.48                28.57
113                71.43              54.76                85.71
...                  ...                ...                  ...
71298               4.76               4.76                  NaN
71310               4.76               4.76                  NaN
71314               4.76               4.76                  NaN
71344               4.76               4.76                  NaN
71364               4.76               4.76                  NaN

[6042 rows x 3 columns]

In [340]:
only_percentiles['Handsize Percentile'] = only_percentiles.mean(axis=1)

<ipython-input-340-2e41c7c9718e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Handsize Percentile'] = only_percentiles.mean(axis=1)

In [341]:
only_percentiles

,Height Percentile,Weight Percentile,Wingspan Percentile,Handsize Percentile
9,69.05,90.48,NaN,79.765000
14,80.95,64.29,NaN,72.620000
29,90.48,90.48,64.29,81.750000
96,61.90,90.48,28.57,60.316667
113,71.43,54.76,85.71,70.633333
...,...,...,...,...
71298,4.76,4.76,NaN,4.760000
71310,4.76,4.76,NaN,4.760000
71314,4.76,4.76,NaN,4.760000
71344,4.76,4.76,NaN,4.760000
71364,4.76,4.76,NaN,4.760000

In [342]:
scipy.stats.scoreatpercentile(metric_dict['Wingspan'], 79.765)

76.4765

In [343]:
only_percentiles['Predicted Hand Size'] = only_percentiles.apply(lambda x: scipy.stats.scoreatpercentile(metric_dict['Hand Size'], x['Handsize Percentile']), axis = 1)

<ipython-input-343-f126448ac53b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted Hand Size'] = only_percentiles.apply(lambda x: scipy.stats.scoreatpercentile(metric_dict['Hand Size'], x['Handsize Percentile']), axis = 1)

In [344]:
# oddly large jump from 75th - 80th percentiles

metric_dict['Hand Size']

[7.09,
 8.25,
 8.27,
 8.66,
 8.66,
 8.66,
 8.816,
 9.0,
 9.06,
 9.06,
 9.06,
 9.25,
 9.45,
 9.45,
 9.84,
 10.14,
 21.0,
 22.0,
 23.0,
 23.0,
 27.0]

In [345]:
only_percentiles

,Height Percentile,Weight Percentile,Wingspan Percentile,Handsize Percentile,Predicted Hand Size
9,69.05,90.48,NaN,79.765000,20.48958
14,80.95,64.29,NaN,72.620000,9.99720
29,90.48,90.48,64.29,81.750000,21.35000
96,61.90,90.48,28.57,60.316667,9.45000
113,71.43,54.76,85.71,70.633333,9.87800
...,...,...,...,...,...
71298,4.76,4.76,NaN,4.760000,8.19432
71310,4.76,4.76,NaN,4.760000,8.19432
71314,4.76,4.76,NaN,4.760000,8.19432
71344,4.76,4.76,NaN,4.760000,8.19432
71364,4.76,4.76,NaN,4.760000,8.19432

In [346]:
qb

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,NaN,NaN,NaN,69.05,90.48,NaN,NaN
14,Sam Huard,74.00,180.0,NaN,NaN,NaN,80.95,64.29,NaN,NaN
29,Ty Thompson,75.25,209.0,75.0,NaN,36.0,90.48,90.48,64.29,NaN
39,Kyle McCord,74.00,207.5,73.0,9.45,31.0,80.95,90.48,40.48,64.29
40,J.J. McCarthy,74.00,181.0,74.5,8.66,NaN,80.95,66.67,57.14,23.81
...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71310,Alvis Shaw,65.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71314,Henry\t Lee,64.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71344,Joe Villarreal,61.00,101.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71364,Jayden Terrell,60.00,86.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN

In [347]:
empty_wingspans = test_qb[test_qb['Wingspan'].isna()]

In [348]:
empty_wingspans.iloc[0]

Full Name             Caleb Williams
Height                          73.0
Weight                         209.0
Wingspan                         NaN
Hand Size                        NaN
Powerball Toss                   NaN
Predicted Wingspan         74.990767
Name: 9, dtype: object

In [349]:
empty_wingspans['Wingspan'] = test_qb[test_qb['Wingspan'].isna()]['Predicted Wingspan']

In [350]:
empty_wingspans

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Predicted Wingspan
9,Caleb Williams,73.0,209.0,74.990767,NaN,NaN,74.990767
14,Sam Huard,74.0,180.0,75.079550,NaN,NaN,75.079550
128,Preston Stone,74.0,215.0,75.836542,NaN,NaN,75.836542
147,Luke Adcock,75.0,200.0,76.228122,NaN,NaN,76.228122
155,Nico Iamaleava,77.0,188.0,77.400592,NaN,NaN,77.400592
...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.0,112.0,66.448772,NaN,NaN,66.448772
71310,Alvis Shaw,65.0,110.0,67.121520,NaN,NaN,67.121520
71314,Henry\t Lee,64.0,110.0,66.405515,NaN,NaN,66.405515
71344,Joe Villarreal,61.0,101.0,64.062845,NaN,NaN,64.062845
71364,Jayden Terrell,60.0,86.0,63.022415,NaN,NaN,63.022415

In [351]:
actual_wingspans = qb[qb['Wingspan'].notna()]

In [352]:
all_wingspans = empty_wingspans.append(actual_wingspans)

In [353]:
all_wingspans.sort_index()

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Predicted Wingspan,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,74.990767,NaN,NaN,74.990767,NaN,NaN,NaN,NaN
14,Sam Huard,74.00,180.0,75.079550,NaN,NaN,75.079550,NaN,NaN,NaN,NaN
29,Ty Thompson,75.25,209.0,75.000000,NaN,36.0,NaN,90.48,90.48,64.29,NaN
39,Kyle McCord,74.00,207.5,73.000000,9.45,31.0,NaN,80.95,90.48,40.48,64.29
40,J.J. McCarthy,74.00,181.0,74.500000,8.66,NaN,NaN,80.95,66.67,57.14,23.81
...,...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,66.448772,NaN,NaN,66.448772,NaN,NaN,NaN,NaN
71310,Alvis Shaw,65.00,110.0,67.121520,NaN,NaN,67.121520,NaN,NaN,NaN,NaN
71314,Henry\t Lee,64.00,110.0,66.405515,NaN,NaN,66.405515,NaN,NaN,NaN,NaN
71344,Joe Villarreal,61.00,101.0,64.062845,NaN,NaN,64.062845,NaN,NaN,NaN,NaN
71364,Jayden Terrell,60.00,86.0,63.022415,NaN,NaN,63.022415,NaN,NaN,NaN,NaN

In [354]:
qb

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,NaN,NaN,NaN,69.05,90.48,NaN,NaN
14,Sam Huard,74.00,180.0,NaN,NaN,NaN,80.95,64.29,NaN,NaN
29,Ty Thompson,75.25,209.0,75.0,NaN,36.0,90.48,90.48,64.29,NaN
39,Kyle McCord,74.00,207.5,73.0,9.45,31.0,80.95,90.48,40.48,64.29
40,J.J. McCarthy,74.00,181.0,74.5,8.66,NaN,80.95,66.67,57.14,23.81
...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71310,Alvis Shaw,65.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71314,Henry\t Lee,64.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71344,Joe Villarreal,61.00,101.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71364,Jayden Terrell,60.00,86.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN

In [355]:
empty_handsizes = qb[qb['Hand Size'].isna()]
empty_handsizes

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,NaN,NaN,NaN,69.05,90.48,NaN,NaN
14,Sam Huard,74.00,180.0,NaN,NaN,NaN,80.95,64.29,NaN,NaN
29,Ty Thompson,75.25,209.0,75.00,NaN,36.0,90.48,90.48,64.29,NaN
96,Tyler Buchner,72.50,206.0,72.25,NaN,37.5,61.90,90.48,28.57,NaN
113,Malachi Nelson,73.50,175.0,77.00,NaN,NaN,71.43,54.76,85.71,NaN
...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71310,Alvis Shaw,65.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71314,Henry\t Lee,64.00,110.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71344,Joe Villarreal,61.00,101.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN
71364,Jayden Terrell,60.00,86.0,NaN,NaN,NaN,4.76,4.76,NaN,NaN

In [356]:
empty_handsizes['Hand Size'] = only_percentiles['Predicted Hand Size']

<ipython-input-356-08029351fb19>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_handsizes['Hand Size'] = only_percentiles['Predicted Hand Size']

In [357]:
empty_handsizes

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,NaN,20.48958,NaN,69.05,90.48,NaN,NaN
14,Sam Huard,74.00,180.0,NaN,9.99720,NaN,80.95,64.29,NaN,NaN
29,Ty Thompson,75.25,209.0,75.00,21.35000,36.0,90.48,90.48,64.29,NaN
96,Tyler Buchner,72.50,206.0,72.25,9.45000,37.5,61.90,90.48,28.57,NaN
113,Malachi Nelson,73.50,175.0,77.00,9.87800,NaN,71.43,54.76,85.71,NaN
...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71310,Alvis Shaw,65.00,110.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71314,Henry\t Lee,64.00,110.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71344,Joe Villarreal,61.00,101.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71364,Jayden Terrell,60.00,86.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN

In [358]:
actual_handsizes = qb[qb['Hand Size'].notna()]
actual_handsizes

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
39,Kyle McCord,74.00,207.5,73.00,9.45,31.0,80.95,90.48,40.48,64.29
40,J.J. McCarthy,74.00,181.0,74.50,8.66,NaN,80.95,66.67,57.14,23.81
58,Drake Maye,76.00,202.5,75.50,8.66,NaN,95.24,90.48,71.43,23.81
65,Jake Garcia,73.00,194.0,75.75,8.66,30.0,69.05,80.95,71.43,23.81
71,Maalik Murphy,75.75,208.0,79.25,9.06,NaN,90.48,90.48,95.24,47.62
...,...,...,...,...,...,...,...,...,...,...
33508,Tevin Carter,73.50,201.0,80.50,8.66,NaN,71.43,90.48,95.24,23.81
33533,Jared Vetetoe,72.50,171.0,NaN,8.27,NaN,61.90,47.62,NaN,14.29
33534,Ty Simpson,73.50,181.0,NaN,8.27,NaN,71.43,66.67,NaN,14.29
33535,Brian Mauer,74.00,179.0,NaN,8.66,NaN,80.95,57.14,NaN,23.81
33539,Tayler Montiel,71.50,146.5,NaN,9.06,NaN,42.86,14.29,NaN,47.62

In [359]:
all_handsizes = empty_handsizes.append(actual_handsizes)
all_handsizes.sort_index()

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,NaN,20.48958,NaN,69.05,90.48,NaN,NaN
14,Sam Huard,74.00,180.0,NaN,9.99720,NaN,80.95,64.29,NaN,NaN
29,Ty Thompson,75.25,209.0,75.0,21.35000,36.0,90.48,90.48,64.29,NaN
39,Kyle McCord,74.00,207.5,73.0,9.45000,31.0,80.95,90.48,40.48,64.29
40,J.J. McCarthy,74.00,181.0,74.5,8.66000,NaN,80.95,66.67,57.14,23.81
...,...,...,...,...,...,...,...,...,...,...
71298,Jkylon\t Ceasar,64.00,112.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71310,Alvis Shaw,65.00,110.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71314,Henry\t Lee,64.00,110.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71344,Joe Villarreal,61.00,101.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN
71364,Jayden Terrell,60.00,86.0,NaN,8.19432,NaN,4.76,4.76,NaN,NaN

In [360]:
all_wingspans

,Full Name,Height,Weight,Wingspan,Hand Size,Powerball Toss,Predicted Wingspan,Height Percentile,Weight Percentile,Wingspan Percentile,Hand Size Percentile
9,Caleb Williams,73.00,209.0,74.990767,NaN,NaN,74.990767,NaN,NaN,NaN,NaN
14,Sam Huard,74.00,180.0,75.079550,NaN,NaN,75.079550,NaN,NaN,NaN,NaN
128,Preston Stone,74.00,215.0,75.836542,NaN,NaN,75.836542,NaN,NaN,NaN,NaN
147,Luke Adcock,75.00,200.0,76.228122,NaN,NaN,76.228122,NaN,NaN,NaN,NaN
155,Nico Iamaleava,77.00,188.0,77.400592,NaN,NaN,77.400592,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
33457,Maddox Kopp,77.00,212.0,77.500000,9.06,NaN,NaN,95.24,95.24,90.48,47.62
33465,Bauer Sharp,76.00,213.0,77.750000,9.06,NaN,NaN,95.24,95.24,90.48,47.62
33479,Nate Yarnell,78.25,195.0,78.500000,9.45,NaN,NaN,95.24,85.71,95.24,64.29
33484,Daniel Shoch,74.00,203.0,78.500000,9.06,NaN,NaN,80.95,90.48,95.24,47.62
33508,Tevin Carter,73.50,201.0,80.500000,8.66,NaN,NaN,71.43,90.48,95.24,23.81

In [361]:
qb['Wingspan'] = all_wingspans['Wingspan']

<ipython-input-361-d9c95b372f00>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb['Wingspan'] = all_wingspans['Wingspan']

In [362]:
qb['Hand Size'] = all_handsizes['Hand Size']

<ipython-input-362-e0edac2688da>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb['Hand Size'] = all_handsizes['Hand Size']

In [363]:
qb = qb[['Full Name', 'Height', 'Weight', 'Wingspan', 'Hand Size']]
qb

             Full Name  Height  Weight   Wingspan  Hand Size
9       Caleb Williams   73.00   209.0  74.990767   20.48958
14           Sam Huard   74.00   180.0  75.079550    9.99720
29         Ty Thompson   75.25   209.0  75.000000   21.35000
39         Kyle McCord   74.00   207.5  73.000000    9.45000
40       J.J. McCarthy   74.00   181.0  74.500000    8.66000
...                ...     ...     ...        ...        ...
71298  Jkylon\t Ceasar   64.00   112.0  66.448772    8.19432
71310       Alvis Shaw   65.00   110.0  67.121520    8.19432
71314      Henry\t Lee   64.00   110.0  66.405515    8.19432
71344   Joe Villarreal   61.00   101.0  64.062845    8.19432
71364   Jayden Terrell   60.00    86.0  63.022415    8.19432

[6345 rows x 5 columns]

### Master Fill NA function 
### Steps
#### Basic Filtering
1. Filter ZCruit-like data for given position and metrics. Save this table as a variable. 

#### EDA: Identify which metrics need to be filled in
2. Identify the number and percentage of NaN values for each metric.
3. Classify metrics into complete (no NaN values), mostly complete (< 10% NaN values), and incomplete (> 10% NaN values). Don't have to worry about complete metrics. Our function will handle mostly complete and incomplete metrics. 

#### Filling in mostly complete metrics
4. For **mostly complete metrics**, we can fit a linear regression model with highest correlated variable to fill in NaN values.
5. Use linear regression model to fill in values for players who are missing values for that metric. 
6. Append the filled-in players with the players who already have values and sort index. Save the complete values as a variable and wait to use at the very end when filling in final complete dataframe.

#### Filling in incomplete metrics
5. For **incomplete metrics**, produce correlations between complete metrics (no NaN values) and/or filled-in mostly complete metrics and incomplete metrics (NaN values). 
6. For incomplete metrics with correlations > 0.4 with any other metrics, produce linear regression model to predict incomplete metrics using the strongest correlation metrics.
7. For incomplete metrics with low correlations, use the average/median percentiles for players as method of filling in Nan values.
8. Fill in values with whatever method for players who are missing values for that metric. 
9. Append the filled-in players with the players who already have values and sort index. Save the complete values as a variable and wait to use at the very end when filling in final complete dataframe.

#### Substituting completed metrics into original dataframe
10. At the very end, used the saved complete values for the mostly complete and incomplete metrics and substitute those in for the original values. Return this dataframe at the end.

In [369]:
qb_full = QB[['Full Name', 'Height', 'Weight', 'Wingspan', 'Hand Size', 'Powerball Toss']]

In [370]:
nan_dict = {}
readable_dict = {}
for column in qb.columns:
    nan_dict[column] = (qb[column].isna().sum() / qb.shape[0])
    readable_dict[column] = "There are {} NaNs out of {} players".format(qb_full[column].isna().sum(), qb_full.shape[0])

In [371]:
readable_dict

{'Full Name': 'There are 0 NaNs out of 6345 players',
 'Height': 'There are 0 NaNs out of 6345 players',
 'Weight': 'There are 0 NaNs out of 6345 players',
 'Wingspan': 'There are 6025 NaNs out of 6345 players',
 'Hand Size': 'There are 6042 NaNs out of 6345 players'}

In [372]:
# Helper function to identify the number and percentage of NaNs for each metric
def nan_counter(data, metrics):
    nan_dict, readable_dict = {}, {}
    for metric in metrics:
        nan_dict[metric] = data[metric].isna().sum() / data.shape[0]
        readable_dict[metric] = "There are {} NaNs out of {} players".format(data[metric].isna().sum(), data.shape[0])
    print(readable_dict)
    return nan_dict

In [373]:
nan_info = nan_counter(qb_full, ["Height", "Weight", "Wingspan", "Hand Size", "Powerball Toss"])

{'Height': 'There are 0 NaNs out of 6345 players', 'Weight': 'There are 0 NaNs out of 6345 players', 'Wingspan': 'There are 6025 NaNs out of 6345 players', 'Hand Size': 'There are 6042 NaNs out of 6345 players', 'Powerball Toss': 'There are 6320 NaNs out of 6345 players'}

In [374]:
nan_info

{'Height': 0.0,
 'Weight': 0.0,
 'Wingspan': 0.9495665878644602,
 'Hand Size': 0.9522458628841608,
 'Powerball Toss': 0.996059889676911}

In [375]:
nan_info.keys()

dict_keys(['Height', 'Weight', 'Wingspan', 'Hand Size', 'Powerball Toss'])

In [376]:
complete_metric, incomplete_metric, drop_metric = [], [], []
for metric in nan_info.keys():
    if nan_info[metric] == 0:
        complete_metric.append(metric)
    elif nan_info[metric] > 0.975:
        drop_metric.append(metric)
    else:
        incomplete_metric.append(metric)

In [377]:
correlations = qb_full.corr()[['Wingspan', 'Hand Size']]
metric_filter = (correlations['Hand Size'] > 0.4) & (correlations['Hand Size'] != 1)
empty_filter = metric_filter[metric_filter].index.values

In [378]:
if len(empty_filter) == 0:
    print("Yes")

Yes

In [380]:
qb_full.drop(columns = ['Powerball Toss'])

             Full Name  Height  Weight  Wingspan  Hand Size
9       Caleb Williams   73.00   209.0       NaN        NaN
14           Sam Huard   74.00   180.0       NaN        NaN
29         Ty Thompson   75.25   209.0      75.0        NaN
39         Kyle McCord   74.00   207.5      73.0       9.45
40       J.J. McCarthy   74.00   181.0      74.5       8.66
...                ...     ...     ...       ...        ...
71298  Jkylon\t Ceasar   64.00   112.0       NaN        NaN
71310       Alvis Shaw   65.00   110.0       NaN        NaN
71314      Henry\t Lee   64.00   110.0       NaN        NaN
71344   Joe Villarreal   61.00   101.0       NaN        NaN
71364   Jayden Terrell   60.00    86.0       NaN        NaN

[6345 rows x 5 columns]

In [381]:
for metric in incomplete_metric:
    all_metrics = incomplete_metric + complete_metric
    all_metrics.remove(metric)
    print(all_metrics)

['Hand Size', 'Height', 'Weight']
['Wingspan', 'Height', 'Weight']

In [382]:
incomplete_metric + complete_metric

['Wingspan', 'Hand Size', 'Height', 'Weight']

In [383]:
        correlations = qb.corr()
        metric_filter = (correlations['Wingspan'] > 0.4) & (correlations['Wingspan'] != 1)
        best_predictors = metric_filter[metric_filter].index.values
        np.append(best_predictors, "Wingspan")

array(['Height', 'Weight', 'Hand Size', 'Wingspan'], dtype=object)

In [577]:
def height_str_to_val(height_str):
    match = re.match("^(\d)'\s*(\d*\.*\d*)", height_str)
    groups = match.groups()
    feet, inches = int(groups[0]), float(groups[1])
    return feet * 12 + inches 
    
def create_percentile(position, event):
    """Take in a position - CB, WR, QB, etc. and an event - Fourty Yard Dash, Weight, 3 Cone and return a list of percentile values of 0, 10th, ... 100th percentile. 
        Reverse for all speed events (lower is better) such as 40, 3 Cone, and Shuttle."""
    sorted_athletes = data[data['Position'] == position]     
    event_values = (sorted_athletes[event].astype(float)).dropna()
    percentile = []
    for i in np.arange(0, 1.01, 0.05):
        percentile.append(event_values.quantile(i))
    if (event == "Forty Yard Dash") or (event == "Shuttle") or (event == "3 Cone"):
        return percentile[::-1]
    return percentile
    
def percentile_to_value(event, percentile, metric_dict):
    if (event == "Forty Yard Dash") or (event == "Shuttle") or (event == "3 Cone"):
        return scipy.stats.scoreatpercentile(metric_dict[event], 100 - percentile)
    else:
        return scipy.stats.scoreatpercentile(metric_dict[event], percentile)
        
def add_score(metric, data, metric_dict):
    # data = data.dropna()
    data[metric + " " + "Percentile"] = data.apply(lambda x: value_to_percentile(metric, x[metric], metric_dict), axis = 1)
    return data

def nan_counter(data, metrics):
    nan_dict, readable_dict = {}, {}
    for metric in metrics:
        nan_dict[metric] = data[metric].isna().sum() / data.shape[0]
        readable_dict[metric] = "There are {} NaNs out of {} players".format(data[metric].isna().sum(), data.shape[0])
    print(readable_dict)
    return nan_dict

def master_fillna(data, position, metrics):
    # Filtering data    
    data['Height'] = data['Height'].apply(height_str_to_val)
    data = data[data["Position"] == position]
    data_with_metrics = data[metrics]
    
    # Getting NaN information
    nan_info = nan_counter(data_with_metrics, metrics)
    
    # Classifying metrics into complete, incomplete, and drop
    complete_metric, incomplete_metric, drop_metric = [], [], []
    for metric in nan_info.keys():
        if nan_info[metric] == 0:
            complete_metric.append(metric)
        elif nan_info[metric] > 0.975:
            drop_metric.append(metric)
        else:
            incomplete_metric.append(metric)
    
    data_with_metrics = data_with_metrics.drop(columns = drop_metric)
    
    metric_dict = {}
    for metric in data_with_metrics.columns:
        metric_dict[metric] = create_percentile(position, metric)
    # We want to fill in the incomplete metrics
    completed_metrics = {}
    for metric in incomplete_metric:
        correlations = data_with_metrics.corr()[metric]
        correlations = correlations[correlations != 1].sort_values(ascending = False)
        metric_filter = correlations > 0.4 
        best_predictors = metric_filter[metric_filter].index.values

        print(metric, best_predictors)
    
    #IF there are no good predictors for linear regression (ie: no metrics with correlation > 0.4 with incomplete metric),
    #then we use the average approach. 
        if len(best_predictors) == 0:
            #For example, if we are predicting Hand Size with the average approach. We want the percentiles for Height, Weight, and Wingspan
            all_other_metrics = incomplete_metric + complete_metric
            all_other_metrics.remove(metric)
            
            all_other_percentiles = data_with_metrics.copy()
            for percentile_metrics in all_other_metrics:
                all_other_percentiles = add_score(percentile_metrics, all_other_percentiles, metric_dict)
                
            empty_metric = all_other_percentiles[all_other_percentiles[metric].isna()]
            full_metric = all_other_percentiles[all_other_percentiles[metric].notna()]
            
            metric_percentile_names =  [x + " " + "Percentile" for x in all_other_metrics]
            only_percentiles = empty_metric[metric_percentile_names]
            
            only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
            
            #40 yard dash is backwards -> FIX
            only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
            empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
            
            all_metric = empty_metric.append(full_metric).sort_index()
            
            completed_metrics[metric] = all_metric[metric].values
            #print(completed_metrics, len(completed_metrics[metric]), np.count_nonzero(~np.isnan(completed_metrics[metric])))

        else:
            full_metric = data_with_metrics[data_with_metrics[metric].notna()]
            empty_metric = data_with_metrics[data_with_metrics[metric].isna()]
            print("There are {} players with metric and {} NaNs.".format(full_metric.shape[0], empty_metric.shape[0]))
            labels = [best_predictors[0]] + [metric]
            predictor = best_predictors[0]
            print(labels)
            full_metric_with_no_predictor_nulls = full_metric[labels].dropna()
            X = full_metric_with_no_predictor_nulls[[predictor]]
            y = full_metric_with_no_predictor_nulls[metric]
            
            reg = LinearRegression(normalize = True).fit(X,y)
            metric_mean = np.median(y)
            
            empty_metric_with_no_predictor_nulls = empty_metric[[predictor]].dropna()
            if len(empty_metric_with_no_predictor_nulls) == 0:
                empty_metric_with_no_predictor_nulls[metric] = metric_mean
            else: 
                empty_metric_with_no_predictor_nulls[metric] = reg.predict(empty_metric_with_no_predictor_nulls)

            empty_metric_with_predictor_nulls = empty_metric[empty_metric[predictor].isna()]
            empty_metric_with_predictor_nulls[metric] = metric_mean
            
            print("There are {} players with a {} (predictor) value and {} players with NaNs for {}.".format(empty_metric_with_no_predictor_nulls.shape[0], best_predictors[0], empty_metric_with_predictor_nulls.shape[0], best_predictors[0]))
            print(empty_metric_with_no_predictor_nulls.shape[0] +  empty_metric_with_predictor_nulls.shape[0] == empty_metric.shape[0])

            empty_metric = empty_metric_with_no_predictor_nulls.append(empty_metric_with_predictor_nulls).sort_index()
            
            all_metric = empty_metric.append(full_metric).sort_index()
            
            completed_metrics[metric] = all_metric[metric].values
            
            train_y = reg.predict(X)
            train_error = mean_squared_error(y, train_y)
            print(reg.coef_)
            print("The RMSE of the model on the training data is {}. The average {} of the training data is {}. On average, predictions are {} from the actual values in the training data".format(np.sqrt(train_error), metric, np.mean(y), np.sqrt(train_error)/np.mean(y)))
            #print(completed_metrics, len(completed_metrics[metric]), np.count_nonzero(~np.isnan(completed_metrics[metric])))
    
    for metric in incomplete_metric:
        print(metric)
        print("There are {} NaN values for this metric".format(data[metric].isna().sum()))
        data[metric] = completed_metrics[metric]
        print("There are {} NaN values for this metric".format(data[metric].isna().sum()))
    
    all_metrics = ["Full Name"] + complete_metric + incomplete_metric
    cleaned_dataset = data[all_metrics]
    
    return cleaned_dataset

In [578]:
master_fillna(data, "FB", ["Height", "Weight", "Forty Yard Dash", "3 Cone", "Shuttle", "Vertical Jump", "Broad Jump"])

{'Height': 'There are 0 NaNs out of 326 players', 'Weight': 'There are 0 NaNs out of 326 players', 'Forty Yard Dash': 'There are 124 NaNs out of 326 players', '3 Cone': 'There are 243 NaNs out of 326 players', 'Shuttle': 'There are 178 NaNs out of 326 players', 'Vertical Jump': 'There are 188 NaNs out of 326 players', 'Broad Jump': 'There are 210 NaNs out of 326 players'}
Forty Yard Dash ['3 Cone']
There are 202 players with metric and 124 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 1 players with a 3 Cone (predictor) value and 123 players with NaNs for 3 Cone.
True
[0.3189473]
The RMSE of the model on the training data is 0.24725003638542256. The average Forty Yard Dash of the training data is 5.328012195121953. On average, predictions are 0.04640568139310786 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 83 players with metric and 243 NaNs.
['Forty Yard Dash', '3 Cone']
There are 120 players with a Forty Yard Dash (predictor) value and 123 players with NaNs for Forty Yard Dash.
True
[1.31867217]
The RMSE of the model on the training data is 0.5027421792397406. The average 3 Cone of the training data is 8.174036585365851. On average, predictions are 0.06150476254777358 from the actual values in the training data
Shuttle ['3 Cone']
There are 148 players with metric and 178 NaNs.
['3 Cone', 'Shuttle']
There are 0 players with a 3 Cone (predictor) value and 178 players with NaNs for 3 Cone.
True
[0.32260573]
The RMSE of the model on the training data is 0.2766550195568667. The average Shuttle of the training data is 4.967999999999998. On average, predictions are 0.05568740329244501 from the actual values in the training data
Vertical Jump ['Broad Jump']
There are 138 players with metric and 188 NaNs.
['Broad Jump', 'Vertical Jump']

<ipython-input-577-dd7e64a46e68>:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-577-dd7e64a46e68>:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-577-dd7e64a46e68>:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

There are 5 players with a Broad Jump (predictor) value and 183 players with NaNs for Broad Jump.
True
[0.42195257]
The RMSE of the model on the training data is 9.439032947477013. The average Vertical Jump of the training data is 24.075108108108104. On average, predictions are 0.39206606695560803 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 116 players with metric and 210 NaNs.
['Vertical Jump', 'Broad Jump']
There are 27 players with a Vertical Jump (predictor) value and 183 players with NaNs for Vertical Jump.
True
[0.4431227]
The RMSE of the model on the training data is 9.672921990508259. The average Broad Jump of the training data is 91.97477477477476. On average, predictions are 0.10516929249563305 from the actual values in the training data
Forty Yard Dash
There are 124 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 243 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 178 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 188 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 210 NaN values for this metric
There are 0 NaN values for this metric

<ipython-input-577-dd7e64a46e68>:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-577-dd7e64a46e68>:133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

,Full Name,Height,Weight,Forty Yard Dash,3 Cone,Shuttle,Vertical Jump,Broad Jump
3292,Joseph Bearns,73.0,252.5,5.3095,8.152000,4.875,22.9,92.0
3916,Takeshi Faupula,70.0,220.0,4.7000,7.345894,4.875,22.9,92.0
7855,Lincoln Parker,69.0,201.0,4.8260,7.512047,4.875,22.9,92.0
8103,Luke McEndoo,72.0,227.0,5.3100,7.558000,4.545,26.0,102.0
8552,Nick Kaires,70.0,193.0,5.2040,7.625000,4.539,24.5,99.0
...,...,...,...,...,...,...,...,...
69668,Davion Cauley,65.0,150.0,5.3095,8.152000,4.875,22.9,92.0
70051,Ayron Rodriguez,66.0,145.0,5.3095,8.152000,4.875,22.9,92.0
70093,Tate Spicer,70.0,145.0,5.3095,8.152000,4.875,22.9,92.0
70204,Austin\t Harris,63.0,143.0,5.3095,8.152000,4.875,22.9,92.0
70434,Jabari Smith,65.0,140.0,5.3095,8.152000,4.875,22.9,92.0

In [530]:
positions = ["WR",
"RB", 
"LB",
"QB", 
"DE", 
"CB", 
"OL",
"DT", 
"S", 
"OT",  
"OG",  
"TE",  
"ATH", 
"DB",  
"DL", 
"OC",  
"K", 
"FB",  
"LS", 
"P"]

combine_metrics = ["Height", "Weight", "Forty Yard Dash", "3 Cone", "Shuttle", "Vertical Jump", "Broad Jump"]

In [532]:
%%time
cleaned_combine_metrics_position_dataframes = {}
for position in positions:
    cleaned_combine_metrics_position_dataframes[position] = master_fillna(data, position, combine_metrics)

{'Height': 'There are 0 NaNs out of 12359 players', 'Weight': 'There are 0 NaNs out of 12359 players', 'Forty Yard Dash': 'There are 6235 NaNs out of 12359 players', '3 Cone': 'There are 9546 NaNs out of 12359 players', 'Shuttle': 'There are 8483 NaNs out of 12359 players', 'Vertical Jump': 'There are 8608 NaNs out of 12359 players', 'Broad Jump': 'There are 8801 NaNs out of 12359 players'}
Forty Yard Dash []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

3 Cone ['Shuttle']
There are 2813 players with metric and 9546 NaNs.
['Shuttle', '3 Cone']
There are 1098 players with a Shuttle (predictor) value and 8448 players with NaNs for Shuttle.
True
[0.9804151]
The RMSE of the model on the training data is 0.3934851927182003. The average 3 Cone of the training data is 7.735904607631389. On average, predictions are 0.05086479379929676 from the actual values in the training data
Shuttle ['3 Cone']
There are 3876 players with metric and 8483 NaNs.
['3 Cone', 'Shuttle']
There are 35 players with a 3 Cone (predictor) value and 8448 players with NaNs for 3 Cone.
True
[0.38332496]
The RMSE of the model on the training data is 0.24604069736686787. The average Shuttle of the training data is 4.6740147588193075. On average, predictions are 0.05264011991032302 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 6235 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 9546 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 8483 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 8608 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 8801 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 9080 players', 'Weight': 'There are 0 NaNs out of 9080 players', 'Forty Yard Dash': 'There are 4197 NaNs out of 9080 players', '3 Cone': 'There are 6916 NaNs out of 9080 players', 'Shuttle': 'There are 6000 NaNs out of 9080 players', 'Vertical Jump': 'There are 6080 NaNs out of 9080 players', 'Broad Jump': 'There are 6206 NaNs out of 9080 players'}
Forty Yard Dash ['3 Cone' 'Shuttle']
There are 4883 players with metric and 4197 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 63 players with a 3 Cone (predictor) value and 4134 players with NaNs for 3 Cone.
True
[0.33403925]
The RMSE of the model on the training data is 0.23836276682738344. The average Forty Yard Dash of the training data is 5.023432175154691. On average, predictions are 0.04745018117419756 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 2164 players with metric and 6916 NaNs.
['Shuttle', '3 Cone']
There are 937 players with a Shuttle (predictor) value and 5979 players with NaNs for Shuttle.
True
[0.99125504]
The RMSE of the model on the training data is 0.3815585200899391. The average 3 Cone of the training data is 7.778692487167526. On average, predictions are 0.04905175525570583 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 3080 players with metric and 6000 NaNs.
['3 Cone', 'Shuttle']
There are 21 players with a 3 Cone (predictor) value and 5979 players with NaNs for 3 Cone.
True
[0.37746799]
The RMSE of the model on the training data is 0.23545532572356265. The average Shuttle of the training data is 4.682819412039187. On average, predictions are 0.05028067602142081 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 4197 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 6916 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 6000 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 6080 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 6206 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 8832 players', 'Weight': 'There are 0 NaNs out of 8832 players', 'Forty Yard Dash': 'There are 4132 NaNs out of 8832 players', '3 Cone': 'There are 6776 NaNs out of 8832 players', 'Shuttle': 'There are 5721 NaNs out of 8832 players', 'Vertical Jump': 'There are 5899 NaNs out of 8832 players', 'Broad Jump': 'There are 6040 NaNs out of 8832 players'}
Forty Yard Dash ['3 Cone']
There are 4700 players with metric and 4132 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 75 players with a 3 Cone (predictor) value and 4057 players with NaNs for 3 Cone.
True
[0.36438056]
The RMSE of the model on the training data is 0.2801563416478388. The average Forty Yard Dash of the training data is 5.216575466935888. On average, predictions are 0.053705029942257704 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 2056 players with metric and 6776 NaNs.
['Forty Yard Dash', '3 Cone']
There are 2719 players with a Forty Yard Dash (predictor) value and 4057 players with NaNs for Forty Yard Dash.
True
[0.99285606]
The RMSE of the model on the training data is 0.4624512995480497. The average 3 Cone of the training data is 7.951437657748613. On average, predictions are 0.05815945737779816 from the actual values in the training data
Shuttle ['3 Cone']
There are 3111 players with metric and 5721 NaNs.
['3 Cone', 'Shuttle']
There are 26 players with a 3 Cone (predictor) value and 5695 players with NaNs for 3 Cone.
True
[0.38032846]
The RMSE of the model on the training data is 0.2942247462739102. The average Shuttle of the training data is 4.792373399014775. On average, predictions are 0.061394370132844295 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 4132 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 6776 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 5721 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 5899 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 6040 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 6345 players', 'Weight': 'There are 0 NaNs out of 6345 players', 'Forty Yard Dash': 'There are 3160 NaNs out of 6345 players', '3 Cone': 'There are 5056 NaNs out of 6345 players', 'Shuttle': 'There are 4329 NaNs out of 6345 players', 'Vertical Jump': 'There are 4447 NaNs out of 6345 players', 'Broad Jump': 'There are 4570 NaNs out of 6345 players'}
Forty Yard Dash ['3 Cone' 'Shuttle']
There are 3185 players with metric and 3160 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 41 players with a 3 Cone (predictor) value and 3119 players with NaNs for 3 Cone.
True
[0.31412836]
The RMSE of the model on the training data is 0.2764445221229421. The average Forty Yard Dash of the training data is 5.166071314102567. On average, predictions are 0.05351155749017475 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 1289 players with metric and 5056 NaNs.
['Forty Yard Dash', '3 Cone']
There are 1937 players with a Forty Yard Dash (predictor) value and 3119 players with NaNs for Forty Yard Dash.
True
[0.89997366]
The RMSE of the model on the training data is 0.46791752857791497. The average 3 Cone of the training data is 7.789097756410256. On average, predictions are 0.06007339273574133 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 2016 players with metric and 4329 NaNs.
['3 Cone', 'Shuttle']
There are 22 players with a 3 Cone (predictor) value and 4307 players with NaNs for 3 Cone.
True
[0.28761287]
The RMSE of the model on the training data is 0.30375361308344234. The average Shuttle of the training data is 4.7240142067876825. On average, predictions are 0.06429989407038511 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 3160 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 5056 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 4329 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 4447 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 4570 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 4229 players', 'Weight': 'There are 0 NaNs out of 4229 players', 'Forty Yard Dash': 'There are 1971 NaNs out of 4229 players', '3 Cone': 'There are 3086 NaNs out of 4229 players', 'Shuttle': 'There are 2536 NaNs out of 4229 players', 'Vertical Jump': 'There are 2634 NaNs out of 4229 players', 'Broad Jump': 'There are 2682 NaNs out of 4229 players'}
Forty Yard Dash ['3 Cone']
There are 2258 players with metric and 1971 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 29 players with a 3 Cone (predictor) value and 1942 players with NaNs for 3 Cone.
True
[0.39453952]
The RMSE of the model on the training data is 0.3353444116966795. The average Forty Yard Dash of the training data is 5.441859964093352. On average, predictions are 0.0616231240622433 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 1143 players with metric and 3086 NaNs.
['Shuttle', '3 Cone']
There are 565 players with a Shuttle (predictor) value and 2521 players with NaNs for Shuttle.
True
[1.03470336]
The RMSE of the model on the training data is 0.529884146063132. The average 3 Cone of the training data is 8.230401595744668. On average, predictions are 0.06438132330469705 from the actual values in the training data
Shuttle ['3 Cone']
There are 1693 players with metric and 2536 NaNs.
['3 Cone', 'Shuttle']
There are 15 players with a 3 Cone (predictor) value and 2521 players with NaNs for 3 Cone.
True
[0.38935601]
The RMSE of the model on the training data is 0.325047208247369. The average Shuttle of the training data is 4.96897606382979. On average, predictions are 0.06541532985305669 from the actual values in the training data
Vertical Jump ['Broad Jump']
There are 1595 players with metric and 2634 NaNs.
['Broad Jump', 'Vertical Jump']

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

There are 149 players with a Broad Jump (predictor) value and 2485 players with NaNs for Broad Jump.
True
[0.25969432]
The RMSE of the model on the training data is 5.225262105190281. The average Vertical Jump of the training data is 23.202470672389108. On average, predictions are 0.22520283201600302 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 1547 players with metric and 2682 NaNs.
['Vertical Jump', 'Broad Jump']
There are 197 players with a Vertical Jump (predictor) value and 2485 players with NaNs for Vertical Jump.
True
[0.87198766]
The RMSE of the model on the training data is 9.57485101358244. The average Broad Jump of the training data is 92.66634477825465. On average, predictions are 0.10332608927755292 from the actual values in the training data
Forty Yard Dash
There are 1971 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 3086 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 2536 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 2634 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 2682 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 3976 players', 'Weight': 'There are 0 NaNs out of 3976 players', 'Forty Yard Dash': 'There are 1743 NaNs out of 3976 players', '3 Cone': 'There are 2645 NaNs out of 3976 players', 'Shuttle': 'There are 2229 NaNs out of 3976 players', 'Vertical Jump': 'There are 2229 NaNs out of 3976 players', 'Broad Jump': 'There are 2305 NaNs out of 3976 players'}
Forty Yard Dash ['Shuttle' '3 Cone']
There are 2233 players with metric and 1743 NaNs.
['Shuttle', 'Forty Yard Dash']
There are 81 players with a Shuttle (predictor) value and 1662 players with NaNs for Shuttle.
True
[0.72924326]
The RMSE of the model on the training data is 0.3043254448264179. The average Forty Yard Dash of the training data is 4.993793517406971. On average, predictions are 0.060940734486843375 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 1331 players with metric and 2645 NaNs.
['Shuttle', '3 Cone']
There are 426 players with a Shuttle (predictor) value and 2219 players with NaNs for Shuttle.
True
[0.96738252]
The RMSE of the model on the training data is 0.3879621482020245. The average 3 Cone of the training data is 7.768277819833468. On average, predictions are 0.049941847755689744 from the actual values in the training data
Shuttle ['Forty Yard Dash' '3 Cone']
There are 1747 players with metric and 2229 NaNs.
['Forty Yard Dash', 'Shuttle']
There are 567 players with a Forty Yard Dash (predictor) value and 1662 players with NaNs for Forty Yard Dash.
True
[0.72947825]
The RMSE of the model on the training data is 0.30437447401069945. The average Shuttle of the training data is 4.647936374549824. On average, predictions are 0.06548593816329504 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 1743 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 2645 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 2229 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 2229 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 2305 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 3781 players', 'Weight': 'There are 0 NaNs out of 3781 players', 'Forty Yard Dash': 'There are 2692 NaNs out of 3781 players', '3 Cone': 'There are 3623 NaNs out of 3781 players', 'Shuttle': 'There are 3499 NaNs out of 3781 players', 'Vertical Jump': 'There are 3573 NaNs out of 3781 players', 'Broad Jump': 'There are 3553 NaNs out of 3781 players'}
Forty Yard Dash ['3 Cone' 'Shuttle' 'Weight']
There are 1089 players with metric and 2692 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 6 players with a 3 Cone (predictor) value and 2686 players with NaNs for 3 Cone.
True
[0.49032055]
The RMSE of the model on the training data is 0.3759501030083768. The average Forty Yard Dash of the training data is 5.778361842105258. On average, predictions are 0.06506171009730417 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle' 'Weight']
There are 158 players with metric and 3623 NaNs.
['Forty Yard Dash', '3 Cone']
There are 937 players with a Forty Yard Dash (predictor) value and 2686 players with NaNs for Forty Yard Dash.
True
[1.21952874]
The RMSE of the model on the training data is 0.5929064566414597. The average 3 Cone of the training data is 8.644368421052627. On average, predictions are 0.06858875371363005 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 282 players with metric and 3499 NaNs.
['3 Cone', 'Shuttle']
There are 1 players with a 3 Cone (predictor) value and 3498 players with NaNs for 3 Cone.
True
[0.36174037]
The RMSE of the model on the training data is 0.31601776155942324. The average Shuttle of the training data is 5.2353057324840755. On average, predictions are 0.06036280930043745 from the actual values in the training data
Vertical Jump ['Broad Jump']
There are 208 players with metric and 3573 NaNs.
['Broad Jump', 'Vertical Jump']
There are 50 players with a Broad Jump (predictor) value and 3523 players with NaNs for Broad Jump.
True
[0.30573538]
The RMSE of the model on the training data is 3.1321022759956083. The average Vertical Jump of the training data is 21.264050561797752. On average, predictions are 0.14729565596606667 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 228 players with metric and 3553 NaNs.
['Vertical Jump', 'Broad Jump']

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

There are 30 players with a Vertical Jump (predictor) value and 3523 players with NaNs for Vertical Jump.
True
[1.82522292]
The RMSE of the model on the training data is 7.652811918465759. The average Broad Jump of the training data is 85.54292134831461. On average, predictions are 0.08946166202700695 from the actual values in the training data
Forty Yard Dash
There are 2692 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 3623 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 3499 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 3573 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 3553 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2994 players', 'Weight': 'There are 0 NaNs out of 2994 players', 'Forty Yard Dash': 'There are 1380 NaNs out of 2994 players', '3 Cone': 'There are 2220 NaNs out of 2994 players', 'Shuttle': 'There are 1785 NaNs out of 2994 players', 'Vertical Jump': 'There are 1933 NaNs out of 2994 players', 'Broad Jump': 'There are 1958 NaNs out of 2994 players'}

<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash ['Shuttle' '3 Cone']
There are 1614 players with metric and 1380 NaNs.
['Shuttle', 'Forty Yard Dash']
There are 40 players with a Shuttle (predictor) value and 1340 players with NaNs for Shuttle.
True
[0.92075159]
The RMSE of the model on the training data is 1.2981026311442778. The average Forty Yard Dash of the training data is 5.76255260906758. On average, predictions are 0.2252652113061263 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 774 players with metric and 2220 NaNs.
['Forty Yard Dash', '3 Cone']
There are 852 players with a Forty Yard Dash (predictor) value and 1368 players with NaNs for Forty Yard Dash.
True
[1.06196738]
The RMSE of the model on the training data is 0.6226738370604947. The average 3 Cone of the training data is 8.696946194225731. On average, predictions are 0.07159683676942995 from the actual values in the training data
Shuttle ['Forty Yard Dash' '3 Cone']
There are 1209 players with metric and 1785 NaNs.
['Forty Yard Dash', 'Shuttle']
There are 445 players with a Forty Yard Dash (predictor) value and 1340 players with NaNs for Forty Yard Dash.
True
[0.60790126]
The RMSE of the model on the training data is 1.054761605451129. The average Shuttle of the training data is 5.28786142001711. On average, predictions are 0.19946846592052256 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 1380 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 2220 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1785 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1933 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1958 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2871 players', 'Weight': 'There are 0 NaNs out of 2871 players', 'Forty Yard Dash': 'There are 1296 NaNs out of 2871 players', '3 Cone': 'There are 2097 NaNs out of 2871 players', 'Shuttle': 'There are 1698 NaNs out of 2871 players', 'Vertical Jump': 'There are 1771 NaNs out of 2871 players', 'Broad Jump': 'There are 1805 NaNs out of 2871 players'}
Forty Yard Dash ['3 Cone']
There are 1575 players with metric and 1296 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 29 players with a 3 Cone (predictor) value and 1267 players with NaNs for 3 Cone.
True
[0.29058831]
The RMSE of the model on the training data is 0.23154522744827644. The average Forty Yard Dash of the training data is 5.05402818791946. On average, predictions are 0.04581399605204701 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 774 players with metric and 2097 NaNs.
['Shuttle', '3 Cone']
There are 405 players with a Shuttle (predictor) value and 1692 players with NaNs for Shuttle.
True
[1.08639262]
The RMSE of the model on the training data is 0.36549165785317933. The average 3 Cone of the training data is 7.733736979166664. On average, predictions are 0.0472593855774705 from the actual values in the training data
Shuttle ['3 Cone']
There are 1173 players with metric and 1698 NaNs.
['3 Cone', 'Shuttle']
There are 6 players with a 3 Cone (predictor) value and 1692 players with NaNs for 3 Cone.
True
[0.41461354]
The RMSE of the model on the training data is 0.22579057383457102. The average Shuttle of the training data is 4.68643359375. On average, predictions are 0.04817961661415487 from the actual values in the training data
Vertical Jump ['Weight']
There are 1100 players with metric and 1771 NaNs.
['Weight', 'Vertical Jump']
There are 1771 players with a Weight (predictor) value and 0 players with NaNs for Weight.
True

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

[0.10556776]
The RMSE of the model on the training data is 4.738640346020219. The average Vertical Jump of the training data is 26.54094727272729. On average, predictions are 0.1785407392331286 from the actual values in the training data
Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 1296 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 2097 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1698 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1771 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1805 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2599 players', 'Weight': 'There are 0 NaNs out of 2599 players', 'Forty Yard Dash': 'There are 1400 NaNs out of 2599 players', '3 Cone': 'There are 2098 NaNs out of 2599 players', 'Shuttle': 'There are 1753 NaNs out of 2599 players', 'Vertical Jump': 'There are 1855 NaNs out of 2599 players', 'Broad Jump': 'There are 1883 NaNs out of 2599 players'}
Forty Yard Dash ['3 Cone' 'Shuttle']
There are 1199 players with metric and 1400 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 8 players with a 3 Cone (predictor) value and 1392 players with NaNs for 3 Cone.
True
[0.38582332]
The RMSE of the model on the training data is 0.3875909375924941. The average Forty Yard Dash of the training data is 5.907594320486823. On average, predictions are 0.06560892921309365 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 501 players with metric and 2098 NaNs.
['Forty Yard Dash', '3 Cone']
There are 706 players with a Forty Yard Dash (predictor) value and 1392 players with NaNs for Forty Yard Dash.
True
[1.16791174]
The RMSE of the model on the training data is 0.6743484918820629. The average 3 Cone of the training data is 8.74145030425963. On average, predictions are 0.07714377688030315 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 846 players with metric and 1753 NaNs.
['3 Cone', 'Shuttle']
There are 5 players with a 3 Cone (predictor) value and 1748 players with NaNs for 3 Cone.
True
[0.30472786]
The RMSE of the model on the training data is 0.37046577715058165. The average Shuttle of the training data is 5.303699596774196. On average, predictions are 0.06985044503197456 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 1400 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 2098 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1753 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1855 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1883 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2421 players', 'Weight': 'There are 0 NaNs out of 2421 players', 'Forty Yard Dash': 'There are 1170 NaNs out of 2421 players', '3 Cone': 'There are 1897 NaNs out of 2421 players', 'Shuttle': 'There are 1506 NaNs out of 2421 players', 'Vertical Jump': 'There are 1647 NaNs out of 2421 players', 'Broad Jump': 'There are 1670 NaNs out of 2421 players'}
Forty Yard Dash ['3 Cone' 'Shuttle']
There are 1251 players with metric and 1170 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 10 players with a 3 Cone (predictor) value and 1160 players with NaNs for 3 Cone.
True
[0.37617723]
The RMSE of the model on the training data is 0.4336956506765183. The average Forty Yard Dash of the training data is 6.01886964980545. On average, predictions are 0.0720559965425629 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 524 players with metric and 1897 NaNs.
['Forty Yard Dash', '3 Cone']
There are 737 players with a Forty Yard Dash (predictor) value and 1160 players with NaNs for Forty Yard Dash.
True
[1.13834481]
The RMSE of the model on the training data is 0.7544417770965877. The average 3 Cone of the training data is 8.911889105058359. On average, predictions are 0.08465565136670844 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 915 players with metric and 1506 NaNs.
['3 Cone', 'Shuttle']
There are 13 players with a 3 Cone (predictor) value and 1493 players with NaNs for 3 Cone.
True
[0.29570313]
The RMSE of the model on the training data is 0.3835822473497442. The average Shuttle of the training data is 5.403970645792566. On average, predictions are 0.07098155643173125 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 1170 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 1897 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1506 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1647 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1670 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2301 players', 'Weight': 'There are 0 NaNs out of 2301 players', 'Forty Yard Dash': 'There are 1343 NaNs out of 2301 players', '3 Cone': 'There are 1986 NaNs out of 2301 players', 'Shuttle': 'There are 1781 NaNs out of 2301 players', 'Vertical Jump': 'There are 1808 NaNs out of 2301 players', 'Broad Jump': 'There are 1845 NaNs out of 2301 players'}
Forty Yard Dash ['3 Cone' 'Shuttle']
There are 958 players with metric and 1343 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 9 players with a 3 Cone (predictor) value and 1334 players with NaNs for 3 Cone.
True
[0.44688351]
The RMSE of the model on the training data is 0.29906932973768674. The average Forty Yard Dash of the training data is 5.341457516339868. On average, predictions are 0.05599021031671863 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 315 players with metric and 1986 NaNs.
['Shuttle', '3 Cone']
There are 212 players with a Shuttle (predictor) value and 1774 players with NaNs for Shuttle.
True
[1.0885051]
The RMSE of the model on the training data is 0.42271793880331726. The average 3 Cone of the training data is 8.062279220779223. On average, predictions are 0.05243156770281908 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 520 players with metric and 1781 NaNs.
['3 Cone', 'Shuttle']
There are 7 players with a 3 Cone (predictor) value and 1774 players with NaNs for 3 Cone.
True
[0.42215254]
The RMSE of the model on the training data is 0.2632510709133001. The average Shuttle of the training data is 4.865876623376629. On average, predictions are 0.05410146851002965 from the actual values in the training data
Vertical Jump ['Broad Jump' 'Height']
There are 493 players with metric and 1808 NaNs.
['Broad Jump', 'Vertical Jump']
There are 48 players with a Broad Jump (predictor) value and 1760 players with NaNs for Broad Jump.
True
[0.27043826]
The RMSE of the model on the training data is 2.970840124720683. The average Vertical Jump of the training data is 23.894453431372536. On average, predictions are 0.12433178826430404 from the actual values in the training data
Broad Jump ['Vertical Jump' 'Height']
There are 456 players with metric and 1845 NaNs.
['Vertical Jump', 'Broad Jump']

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

There are 85 players with a Vertical Jump (predictor) value and 1760 players with NaNs for Vertical Jump.
True
[2.0019855]
The RMSE of the model on the training data is 8.083057672176594. The average Broad Jump of the training data is 96.14485294117648. On average, predictions are 0.08407166296381965 from the actual values in the training data
Forty Yard Dash
There are 1343 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 1986 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1781 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1808 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1845 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2247 players', 'Weight': 'There are 0 NaNs out of 2247 players', 'Forty Yard Dash': 'There are 1202 NaNs out of 2247 players', '3 Cone': 'There are 1689 NaNs out of 2247 players', 'Shuttle': 'There are 1497 NaNs out of 2247 players', 'Vertical Jump': 'There are 1487 NaNs out of 2247 players', 'Broad Jump': 'There are 1505 NaNs out of 2247 players'}
Forty Yard Dash ['3 Cone' 'Shuttle']
There are 1045 players with metric and 1202 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 27 players with a 3 Cone (predictor) value and 1175 players with NaNs for 3 Cone.
True
[0.51127988]
The RMSE of the model on the training data is 0.33975283400619066. The average Forty Yard Dash of the training data is 5.111137476459507. On average, predictions are 0.06647303766940309 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 558 players with metric and 1689 NaNs.
['Shuttle', '3 Cone']
There are 197 players with a Shuttle (predictor) value and 1492 players with NaNs for Shuttle.
True
[1.08937538]
The RMSE of the model on the training data is 0.43460694632039665. The average 3 Cone of the training data is 7.756059674502714. On average, predictions are 0.05603450264173758 from the actual values in the training data
Shuttle ['3 Cone' 'Forty Yard Dash']
There are 750 players with metric and 1497 NaNs.
['3 Cone', 'Shuttle']
There are 5 players with a 3 Cone (predictor) value and 1492 players with NaNs for 3 Cone.
True
[0.45984859]
The RMSE of the model on the training data is 0.2823678937804641. The average Shuttle of the training data is 4.7094502712477375. On average, predictions are 0.05995771852701878 from the actual values in the training data
Vertical Jump ['Broad Jump']
There are 760 players with metric and 1487 NaNs.
['Broad Jump', 'Vertical Jump']
There are 49 players with a Broad Jump (predictor) value and 1438 players with NaNs for Broad Jump.
True

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

[0.26484887]
The RMSE of the model on the training data is 3.5984996299403456. The average Vertical Jump of the training data is 25.856718614718655. On average, predictions are 0.1391707773735813 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 742 players with metric and 1505 NaNs.
['Vertical Jump', 'Broad Jump']
There are 67 players with a Vertical Jump (predictor) value and 1438 players with NaNs for Vertical Jump.
True
[1.61372904]
The RMSE of the model on the training data is 8.882551013142571. The average Broad Jump of the training data is 100.44199134199133. On average, predictions are 0.08843463669391712 from the actual values in the training data
Forty Yard Dash
There are 1202 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 1689 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1497 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1487 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1505 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2172 players', 'Weight': 'There are 0 NaNs out of 2172 players', 'Forty Yard Dash': 'There are 1263 NaNs out of 2172 players', '3 Cone': 'There are 1988 NaNs out of 2172 players', 'Shuttle': 'There are 1909 NaNs out of 2172 players', 'Vertical Jump': 'There are 1938 NaNs out of 2172 players', 'Broad Jump': 'There are 1943 NaNs out of 2172 players'}

<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash ['3 Cone']
There are 909 players with metric and 1263 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 7 players with a 3 Cone (predictor) value and 1256 players with NaNs for 3 Cone.
True
[0.3416323]
The RMSE of the model on the training data is 0.20746538668152303. The average Forty Yard Dash of the training data is 4.959129943502822. On average, predictions are 0.04183503740476345 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash']
There are 184 players with metric and 1988 NaNs.
['Shuttle', '3 Cone']
There are 80 players with a Shuttle (predictor) value and 1908 players with NaNs for Shuttle.
True
[1.01686]
The RMSE of the model on the training data is 0.3218403088082438. The average 3 Cone of the training data is 7.725311475409837. On average, predictions are 0.04166049612791435 from the actual values in the training data
Shuttle ['3 Cone']
There are 263 players with metric and 1909 NaNs.
['3 Cone', 'Shuttle']
There are 1 players with a 3 Cone (predictor) value and 1908 players with NaNs for 3 Cone.
True
[0.41413636]
The RMSE of the model on the training data is 0.20539105892523532. The average Shuttle of the training data is 4.637628415300547. On average, predictions are 0.044287950765439815 from the actual values in the training data
Vertical Jump ['Broad Jump' 'Weight']
There are 234 players with metric and 1938 NaNs.
['Broad Jump', 'Vertical Jump']
There are 16 players with a Broad Jump (predictor) value and 1922 players with NaNs for Broad Jump.
True

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

[0.18553398]
The RMSE of the model on the training data is 3.5378804634103185. The average Vertical Jump of the training data is 27.23741784037558. On average, predictions are 0.1298904501206394 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 229 players with metric and 1943 NaNs.
['Vertical Jump', 'Broad Jump']
There are 21 players with a Vertical Jump (predictor) value and 1922 players with NaNs for Vertical Jump.
True
[1.35719881]
The RMSE of the model on the training data is 9.568704818899986. The average Broad Jump of the training data is 104.68732394366198. On average, predictions are 0.09140270720884444 from the actual values in the training data
Forty Yard Dash
There are 1263 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 1988 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1909 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1938 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1943 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 2060 players', 'Weight': 'There are 0 NaNs out of 2060 players', 'Forty Yard Dash': 'There are 1242 NaNs out of 2060 players', '3 Cone': 'There are 1893 NaNs out of 2060 players', 'Shuttle': 'There are 1834 NaNs out of 2060 players', 'Vertical Jump': 'There are 1862 NaNs out of 2060 players', 'Broad Jump': 'There are 1869 NaNs out of 2060 players'}

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash ['3 Cone']
There are 818 players with metric and 1242 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 2 players with a 3 Cone (predictor) value and 1240 players with NaNs for 3 Cone.
True
[0.47374645]
The RMSE of the model on the training data is 0.31310664624377166. The average Forty Yard Dash of the training data is 5.4746424242424245. On average, predictions are 0.057192163794532944 from the actual values in the training data
3 Cone ['Shuttle' 'Forty Yard Dash' 'Weight']
There are 167 players with metric and 1893 NaNs.
['Shuttle', '3 Cone']
There are 62 players with a Shuttle (predictor) value and 1831 players with NaNs for Shuttle.
True
[1.37414816]
The RMSE of the model on the training data is 0.4211549420942972. The average 3 Cone of the training data is 8.33339634146342. On average, predictions are 0.05053821093313541 from the actual values in the training data
Shuttle ['3 Cone']
There are 226 players with metric and 1834 NaNs.
['3 Cone', 'Shuttle']
There are 3 players with a 3 Cone (predictor) value and 1831 players with NaNs for 3 Cone.
True
[0.42879943]
The RMSE of the model on the training data is 0.23526223642237726. The average Shuttle of the training data is 5.009597560975608. On average, predictions are 0.04696230257197755 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 1242 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 1893 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 1834 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 1862 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 1869 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 1304 players', 'Weight': 'There are 0 NaNs out of 1304 players', 'Forty Yard Dash': 'There are 555 NaNs out of 1304 players', '3 Cone': 'There are 990 NaNs out of 1304 players', 'Shuttle': 'There are 748 NaNs out of 1304 players', 'Vertical Jump': 'There are 831 NaNs out of 1304 players', 'Broad Jump': 'There are 828 NaNs out of 1304 players'}
Forty Yard Dash ['3 Cone']
There are 749 players with metric and 555 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 1 players with a 3 Cone (predictor) value and 554 players with NaNs for 3 Cone.
True
[0.39113485]
The RMSE of the model on the training data is 0.4592144843219958. The average Forty Yard Dash of the training data is 5.971006389776359. On average, predictions are 0.07690738450862644 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 314 players with metric and 990 NaNs.
['Forty Yard Dash', '3 Cone']
There are 436 players with a Forty Yard Dash (predictor) value and 554 players with NaNs for Forty Yard Dash.
True
[1.09091231]
The RMSE of the model on the training data is 0.7669150136775134. The average 3 Cone of the training data is 8.71409584664537. On average, predictions are 0.0880085584521944 from the actual values in the training data
Shuttle ['3 Cone']
There are 556 players with metric and 748 NaNs.
['3 Cone', 'Shuttle']
There are 3 players with a 3 Cone (predictor) value and 745 players with NaNs for 3 Cone.
True
[0.2859654]
The RMSE of the model on the training data is 0.4427862241147125. The average Shuttle of the training data is 5.370369774919616. On average, predictions are 0.08244985777005275 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 555 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 990 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 748 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 831 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 828 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 783 players', 'Weight': 'There are 0 NaNs out of 783 players', 'Forty Yard Dash': 'There are 472 NaNs out of 783 players', '3 Cone': 'There are 771 NaNs out of 783 players', 'Shuttle': 'There are 671 NaNs out of 783 players', 'Vertical Jump': 'There are 702 NaNs out of 783 players', 'Broad Jump': 'There are 731 NaNs out of 783 players'}
Forty Yard Dash ['Shuttle']
There are 311 players with metric and 472 NaNs.
['Shuttle', 'Forty Yard Dash']
There are 4 players with a Shuttle (predictor) value and 468 players with NaNs for Shuttle.
True
[0.39526812]
The RMSE of the model on the training data is 0.22924841682511396. The average Forty Yard Dash of the training data is 4.929814814814814. On average, predictions are 0.04650243983530354 from the actual values in the training data
Shuttle ['Forty Yard Dash']
There are 112 players with metric and 671 NaNs.
['Forty Yard Dash', 'Shuttle']
There are 203 players with a Forty Yard Dash (predictor) value and 468 players with NaNs for Forty Yard Dash.
True
[0.9308189]
The RMSE of the model on the training data is 0.351797739339076. The average Shuttle of the training data is 4.683203703703704. On average, predictions are 0.07511903423309503 from the actual values in the training data
Vertical Jump []

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

Broad Jump []

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash
There are 472 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 671 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 702 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 731 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 326 players', 'Weight': 'There are 0 NaNs out of 326 players', 'Forty Yard Dash': 'There are 124 NaNs out of 326 players', '3 Cone': 'There are 243 NaNs out of 326 players', 'Shuttle': 'There are 178 NaNs out of 326 players', 'Vertical Jump': 'There are 188 NaNs out of 326 players', 'Broad Jump': 'There are 210 NaNs out of 326 players'}
Forty Yard Dash ['3 Cone']
There are 202 players with metric and 124 NaNs.
['3 Cone', 'Forty Yard Dash']
There are 1 players with a 3 Cone (predictor) value and 123 players with NaNs for 3 Cone.
True
[0.3189473]
The RMSE of the model on the training data is 0.24725003638542256. The average Forty Yard Dash of the training data is 5.328012195121953. On average, predictions are 0.04640568139310786 from the actual values in the training data
3 Cone ['Forty Yard Dash' 'Shuttle']
There are 83 players with metric and 243 NaNs.
['Forty Yard Dash', '3 Cone']
There are 120 players with a Forty Yard Dash (predictor) value and 123 players with NaNs for Forty Yard Dash.
True
[1.31867217]
The RMSE of the model on the training data is 0.5027421792397406. The average 3 Cone of the training data is 8.174036585365851. On average, predictions are 0.06150476254777358 from the actual values in the training data
Shuttle ['3 Cone']
There are 148 players with metric and 178 NaNs.
['3 Cone', 'Shuttle']
There are 0 players with a 3 Cone (predictor) value and 178 players with NaNs for 3 Cone.
True
[0.32260573]
The RMSE of the model on the training data is 0.2766550195568667. The average Shuttle of the training data is 4.967999999999998. On average, predictions are 0.05568740329244501 from the actual values in the training data
Vertical Jump ['Broad Jump']
There are 138 players with metric and 188 NaNs.
['Broad Jump', 'Vertical Jump']
There are 5 players with a Broad Jump (predictor) value and 183 players with NaNs for Broad Jump.
True
[0.42195257]
The RMSE of the model on the training data is 9.439032947477013. The average Vertical Jump of the training data is 24.075108108108104. On average, predictions are 0.39206606695560803 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 116 players with metric and 210 NaNs.
['Vertical Jump', 'Broad Jump']

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

There are 27 players with a Vertical Jump (predictor) value and 183 players with NaNs for Vertical Jump.
True
[0.4431227]
The RMSE of the model on the training data is 9.672921990508259. The average Broad Jump of the training data is 91.97477477477476. On average, predictions are 0.10516929249563305 from the actual values in the training data
Forty Yard Dash
There are 124 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 243 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 178 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 188 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 210 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 277 players', 'Weight': 'There are 0 NaNs out of 277 players', 'Forty Yard Dash': 'There are 124 NaNs out of 277 players', '3 Cone': 'There are 245 NaNs out of 277 players', 'Shuttle': 'There are 197 NaNs out of 277 players', 'Vertical Jump': 'There are 218 NaNs out of 277 players', 'Broad Jump': 'There are 223 NaNs out of 277 players'}
Forty Yard Dash ['Shuttle' '3 Cone']
There are 153 players with metric and 124 NaNs.
['Shuttle', 'Forty Yard Dash']
There are 2 players with a Shuttle (predictor) value and 122 players with NaNs for Shuttle.
True
[0.37663627]
The RMSE of the model on the training data is 0.346700476618078. The average Forty Yard Dash of the training data is 5.246935897435898. On average, predictions are 0.06607675096383502 from the actual values in the training data
3 Cone ['Forty Yard Dash']
There are 32 players with metric and 245 NaNs.
['Forty Yard Dash', '3 Cone']
There are 122 players with a Forty Yard Dash (predictor) value and 123 players with NaNs for Forty Yard Dash.
True
[1.02080166]
The RMSE of the model on the training data is 0.8143436996711448. The average 3 Cone of the training data is 7.890935483870968. On average, predictions are 0.1031998932617887 from the actual values in the training data
Shuttle ['Forty Yard Dash']
There are 80 players with metric and 197 NaNs.
['Forty Yard Dash', 'Shuttle']
There are 75 players with a Forty Yard Dash (predictor) value and 122 players with NaNs for Forty Yard Dash.
True
[0.78857596]
The RMSE of the model on the training data is 0.5016665429484962. The average Shuttle of the training data is 4.8887820512820515. On average, predictions are 0.10261585353696376 from the actual values in the training data
Vertical Jump ['Broad Jump']
There are 59 players with metric and 218 NaNs.
['Broad Jump', 'Vertical Jump']

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean

There are 12 players with a Broad Jump (predictor) value and 206 players with NaNs for Broad Jump.
True
[0.340313]
The RMSE of the model on the training data is 3.783957517522528. The average Vertical Jump of the training data is 23.08738095238095. On average, predictions are 0.1638972183690804 from the actual values in the training data
Broad Jump ['Vertical Jump']
There are 54 players with metric and 223 NaNs.
['Vertical Jump', 'Broad Jump']
There are 17 players with a Vertical Jump (predictor) value and 206 players with NaNs for Vertical Jump.
True
[1.36343383]
The RMSE of the model on the training data is 7.5739775507506435. The average Broad Jump of the training data is 91.75952380952381. On average, predictions are 0.08254159607969253 from the actual values in the training data
Forty Yard Dash
There are 124 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 245 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 197 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 218 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 223 NaN values for this metric
There are 0 NaN values for this metric
{'Height': 'There are 0 NaNs out of 165 players', 'Weight': 'There are 0 NaNs out of 165 players', 'Forty Yard Dash': 'There are 98 NaNs out of 165 players', '3 Cone': 'There are 160 NaNs out of 165 players', 'Shuttle': 'There are 140 NaNs out of 165 players', 'Vertical Jump': 'There are 150 NaNs out of 165 players', 'Broad Jump': 'There are 149 NaNs out of 165 players'}

<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

Forty Yard Dash ['Shuttle' '3 Cone']
There are 67 players with metric and 98 NaNs.
['Shuttle', 'Forty Yard Dash']
There are 0 players with a Shuttle (predictor) value and 98 players with NaNs for Shuttle.
True
[1.08110352]
The RMSE of the model on the training data is 0.5386091734241818. The average Forty Yard Dash of the training data is 5.500440000000001. On average, predictions are 0.09792110693402377 from the actual values in the training data
3 Cone ['Forty Yard Dash']
There are 5 players with metric and 160 NaNs.
['Forty Yard Dash', '3 Cone']

<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric_with_predictor_nulls[metric] = metric_mean
<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]

There are 62 players with a Forty Yard Dash (predictor) value and 98 players with NaNs for Forty Yard Dash.
True
[0.73137473]
The RMSE of the model on the training data is 0.4830818842683432. The average 3 Cone of the training data is 7.9136. On average, predictions are 0.061044516309687526 from the actual values in the training data
Shuttle ['Forty Yard Dash']
There are 25 players with metric and 140 NaNs.
['Forty Yard Dash', 'Shuttle']
There are 42 players with a Forty Yard Dash (predictor) value and 98 players with NaNs for Forty Yard Dash.
True
[0.89255936]
The RMSE of the model on the training data is 0.48939401999631454. The average Shuttle of the training data is 5.318079999999998. On average, predictions are 0.09202456901669676 from the actual values in the training data
Vertical Jump []
Broad Jump []
Forty Yard Dash
There are 98 NaN values for this metric
There are 0 NaN values for this metric
3 Cone
There are 160 NaN values for this metric
There are 0 NaN values for this metric
Shuttle
There are 140 NaN values for this metric
There are 0 NaN values for this metric
Vertical Jump
There are 150 NaN values for this metric
There are 0 NaN values for this metric
Broad Jump
There are 149 NaN values for this metric
There are 0 NaN values for this metric
Wall time: 54.9 s

<ipython-input-525-a0554d95919f>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles[metric + " " + "Percentile"] = only_percentiles.mean(axis=1)
<ipython-input-525-a0554d95919f>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_percentiles['Predicted' + " " + metric] = only_percentiles.apply(lambda x: percentile_to_value(metric, x[metric + " " + "Percentile"], metric_dict), axis = 1)
<ipython-input-525-a0554d95919f>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_metric[metric] = only_percentiles['Predicted' + " " + metric]
<ipython-input-525-a0554d95919f>:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[metric] = completed_metrics[metric]

In [557]:
cleaned_combine_metrics_position_dataframes['P']

,Full Name,Height,Weight,Forty Yard Dash,3 Cone,Shuttle,Vertical Jump,Broad Jump
1414,Christian Silverstein,71.0,155.0,4.9,8.060000,4.600000,24.846000,95.000000
1415,Noah Jones,70.0,145.0,4.9,8.060000,4.600000,22.708180,93.214000
1477,Caden Noonkester,78.0,175.0,5.0,7.917842,4.871408,29.722367,98.690033
1494,Sebastian Tasko,73.0,175.0,4.9,8.060000,4.600000,29.583300,98.352300
1559,Gabe Nwosu,77.0,215.0,4.9,8.060000,4.600000,34.034160,118.146000
...,...,...,...,...,...,...,...,...
66890,Robert Reed,74.0,170.0,4.9,8.060000,4.600000,29.749900,98.756900
66942,Luca Weber,73.0,170.0,4.9,8.060000,4.600000,28.849350,97.488625
67102,Caden McNeese,69.0,170.0,4.9,8.060000,4.600000,24.848000,95.000000
67253,Gavin Gundaker,71.0,170.0,4.9,8.060000,4.600000,27.866480,96.666000
67688,Kaden Wooster,73.0,165.0,4.9,8.060000,4.600000,28.388370,97.128475

In [414]:
yay = qb.corr()
filters = (yay['Wingspan'] > 0.4) & (yay['Wingspan'] != 1)
filters[filters].index.values

array(['Height', 'Weight', 'Hand Size'], dtype=object)

In [420]:
yay = qb.corr()['Wingspan'].sort_values(ascending = False)

False

In [447]:
yay = qb.corr()['Wingspan']
yay[yay != 1]

Height       0.963743
Weight       0.740676
Hand Size    0.639713
Name: Wingspan, dtype: float64

In [445]:
        correlations = qb.corr()
        correlations = correlations[correlations != 1].sort_values(ascending = False)
        metric_filter = (correlations[metric] > 0.4)
        best_predictors = metric_filter[metric_filter].index.values

             Height    Weight  Wingspan  Hand Size
Height     1.000000  0.642136  0.963743   0.610323
Weight     0.642136  1.000000  0.740676   0.622004
Wingspan   0.963743  0.740676  1.000000   0.639713
Hand Size  0.610323  0.622004  0.639713   1.000000

In [462]:
correlations = qb.corr()['Hand Size']
correlations = correlations[correlations != 1].sort_values(ascending = False)
filters = correlations > 0.6
filters[filters].index.values[0]

'Wingspan'

9        74.990767
14       75.079550
29       75.000000
39       73.000000
40       74.500000
           ...
71298    66.448772
71310    67.121520
71314    66.405515
71344    64.062845
71364    63.022415
Name: Wingspan, Length: 6345, dtype: float64